name: Football Predictions

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: pip install requests numpy
    
    - name: Fetch and Predict
      env:
        API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
      run: |
        echo "Starting prediction pipeline..."
        echo "Current date: $(date)"
        python src/fetch_data.py
        python src/predict.py
        echo "Pipeline complete"
    
    - name: Show Results
      run: |
        echo "=== Data Files ==="
        ls -la data/ 2>/dev/null || echo "No data directory"
        echo ""
        echo "=== Predictions ==="
        if [ -f predictions.json ]; then
          echo "predictions.json exists ($(wc -c < predictions.json) bytes)"
          head -50 predictions.json
        else
          echo "No predictions.json found"
        fi
    
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update predictions - $(date +'%Y-%m-%d %H:%M')"
        git push || echo "No changes to push"
