name: Football Predictions

on:
  schedule:
    # Runs every day at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  predict:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Fetch latest data from Football-Data.org
      env:
        API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
      run: |
        echo "Fetching upcoming matches for 2025/26 season..."
        python src/fetch_data.py
    
    - name: Generate predictions
      run: |
        echo "Generating predictions..."
        python src/predict.py
    
    - name: Commit predictions
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add predictions.json
        git add data/
        git diff --quiet && git diff --staged --quiet || git commit -m "Update predictions - $(date +'%Y-%m-%d %H:%M')"
        git push
