name: Football Predictions

on:
  schedule:
    # Runs every day at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  predict:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Clean old predictions
      run: |
        echo "🧹 Cleaning old data..."
        # Remove predictions older than today
        if [ -f predictions.json ]; then
          echo "Current predictions.json will be replaced"
        fi
    
    - name: Fetch latest data
      env:
        API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
      run: |
        echo "📅 Fetching matches for next 14 days..."
        echo "Current date: $(date +'%Y-%m-%d')"
        python src/fetch_data.py
    
    - name: Generate predictions
      run: |
        echo "🔮 Generating predictions with rolling form..."
        python src/predict.py
    
    - name: Verify output
      run: |
        if [ -f predictions.json ]; then
          echo "✅ Predictions generated successfully"
          echo "File size: $(stat -c%s predictions.json) bytes"
          echo ""
          echo "Preview (first 20 lines):"
          head -20 predictions.json
        else
          echo "❌ Failed to generate predictions"
          exit 1
        fi
    
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add predictions.json
        git add data/
        git diff --quiet && git diff --staged --quiet || (
          git commit -m "🔄 Update predictions - $(date +'%Y-%m-%d %H:%M')"
          git push
        )
